#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width        5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle 	 false

bspc config normal_border_color  "#222833"
bspc config focused_border_color "#6c6b84"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc node -d next.desktop --to-monitor next

xsetroot -cursor_name left_ptr &
#feh --no-startup-id feh --bg-fill -Z ~/.config/bspwm/assets/fuyuko.jpg \
#feh --no-startup-id feh --bg-scale -Z ~/.config/bspwm/assets/voca.jpg \
feh --no-startup-id feh --bg-scale -Z ~/.config/bspwm/assets/miku_wall.jpg \
#feh --no-startup-id feh --bg-scale -Z /home/aya/Downloads/maid-set/Photo_1693072337717.jpg \
--bg-fill ~/.config/bspwm/assets/fuyuko2.jpg &
dunst -config $HOME/.config/dunst/dunstrc
setxkbmap -layout us -option ctrl:swapcaps
$HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/scripts/low_batt.sh
