#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


# bspc monitor -r

# # Get the list of connected monitors
# MONITORS=$(xrandr --query | grep " connected" | cut -d' ' -f1)

# # Assign workspaces based on the number of monitors
# if [[ $(echo "$MONITORS" | wc -l) -eq 2 ]]; then
#     # If there are two monitors connected
#     bspc monitor DP1 -d 一 二 三 四 五 
#     bspc monitor eDP1 -d 六 七 八 九 十
# else
    # If there is only one monitor
#     bspc monitor -d 一 二 三 四 五 六 七 八 九 十
# fi
#

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width        5
bspc config window_gap          12
bspc config pointer_follows_monitor true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle 	 false

bspc config normal_border_color  "#222833"
bspc config focused_border_color "#6c6b84"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc node -d next.desktop --to-monitor next

xsetroot -cursor_name left_ptr &
picom &
mpd &
#feh --no-startup-id feh --bg-fill -Z ~/.config/bspwm/assets/fuyuko.jpg \
#feh --no-startup-id feh --bg-scale -Z ~/.config/bspwm/assets/voca.jpg \
feh --no-startup-id feh --bg-scale -Z ~/.config/bspwm/assets/miku_wall.jpg --bg-fill ~/.config/bspwm/assets/hatsune_miku.jpg &
#feh --no-startup-id feh --bg-scale -Z /home/aya/Downloads/maid-set/Photo_1693072337717.jpg \
dunst -config $HOME/.config/dunst/dunstrc
setxkbmap -layout us -option ctrl:swapcaps
$HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/scripts/low_batt.sh
