#!/bin/sh

# Start sxhkd if not already running
pgrep -x sxhkd > /dev/null || sxhkd &

# Set up workspaces for the monitor
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# General bspwm configuration
bspc config border_width              5
bspc config window_gap                12
bspc config pointer_follows_monitor   true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true

bspc config split_ratio               0.52
bspc config borderless_monocle        false
bspc config gapless_monocle           false
bspc config single_monocle            false

bspc config normal_border_color       "#222833"
bspc config focused_border_color      "#6c6b84"

# bspwm rules for specific applications
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Move node to the next desktop and monitor (if applicable)
bspc node -d next.desktop --to-monitor next

# Start essential services
xsetroot -cursor_name left_ptr &
picom --config $HOME/.config/picom/picom.conf &
mpd &

# Set wallpaper with feh
feh \
    --bg-scale -Z ~/.config/bspwm/assets/miku_wall.jpg \
    --bg-fill ~/.config/bspwm/assets/miku_rotate.jpg &

# Notifications
dunst -config $HOME/.config/dunst/dunstrc &

# Keyboard layout and options
setxkbmap -layout us -option ctrl:swapcaps &

# Launch polybar
$HOME/.config/polybar/launch.sh &

# Monitor low battery
$HOME/.config/bspwm/scripts/low_batt.sh &

#libinput-gestures: touchpad gestures
libinput-gestures-setup restart
