[window]
decorations = "None"
opacity = 1.0
option_as_alt = "Both"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font]
size = 14

[cursor]
style = "beam"

[colors.primary]
background = '#181818'
foreground = '#d8d8d8'

[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

# Normal colors (grayscale)
[colors.normal]
black   = '#181818' # darkest bg
red     = '#585858' # reused for dim accents
green   = '#888888'
yellow  = '#aaaaaa'
blue    = '#b0b0b0'
magenta = '#c0c0c0'
cyan    = '#d0d0d0'
white   = '#d8d8d8'

# Bright colors (lighter grayscale steps)
[colors.bright]
black   = '#585858'
red     = '#888888'
green   = '#aaaaaa'
yellow  = '#b0b0b0'
blue    = '#c0c0c0'
magenta = '#d0d0d0'
cyan    = '#e0e0e0'
white   = '#f8f8f8'

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"
